### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by hapination** [kimmolinna/pycaruna#11]
I started getting the following error about a week ago, maybe the caruna site has changed?

Traceback (most recent call last):
  File "/Users/hannuteras/git/tuya/caruna/caruna.py", line 46, in <module>
    (session,info) = pycaruna.login_caruna(username, password)
  File "/Users/hannuteras/git/tuya/caruna/pycaruna.py", line 50, in login_caruna
    soup = BeautifulSoup(s.get(str(url)).content,'lxml')
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tuya/lib/python3.10/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tuya/lib/python3.10/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tuya/lib/python3.10/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tuya/lib/python3.10/site-packages/requests/models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tuya/lib/python3.10/site-packages/requests/models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'e,chrome=1': No scheme supplied. Perhaps you meant http://e,chrome=1?

**Comment by kimmolinna** [comment]
I will check this later on today.

**Comment by mattivisti** [comment]
The same here. Already check that error parser (finds) the meta content e,chrome=1 ... Should it takes some real web address?

**Comment by terop** [comment]
Caruna changed the login sequence by adding three (maybe four) new redirects. These need to be handled in order to get the parameters which are needed for OAuth token acquisition. You can see this for yourself if you use your browser's developer tool ("persist state" need to be enabled so you see all the redirects) from the log in page forwards.
I did try some code changes yesterday to handle this but unfortunately my attempts were unsuccessful. I may continue with this today.

**Comment by kimmolinna** [comment]
Actually Caruna just changed the name of the login form. It's fixed now.
