### ISSUE TITLE
Authentication to Caruna fails

### ISSUE THREAD

**Issue by masipila** [kimmolinna/pycaruna#14]
The authentication to Caruna portal seems to have changed...

I get the following stack trace
```
Traceback (most recent call last):
  File "/path/to/my/script", line 67, in <module>
    (session,info) = pycaruna.login_caruna(username, password)
  File "/path/to/pycaruna.py", line 49, in login_caruna
    soup = BeautifulSoup(s.get(str(url)).content,'lxml')
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'e,chrome=1': No schema supplied. Perhaps you meant http://e,chrome=1?
```
The Caruna site is so javascript-heavy that further debugging is unfortunately way beyound my skills...

Cheers,
Markus

**Comment by jarmoruuth** [comment]
My knowledge for this kind of code is close to zero. But anyway I managed to tweak the code and make it work again. Below is my one line change, just a small index adjustment.

    #orig action=soup.find('form')['action'][1:][:17]+"0-userIDPanel-usernameLogin-loginWithUserID"  # type: ignore
    action=soup.find('form')['action'][1:][:11]+"0-userIDPanel-usernameLogin-loginWithUserID"  # type: ignore

**Comment by kimmolinna** [comment]
Thank you @jarmoruuth for the fix.
