### ISSUE TITLE
Pycaruna stopped working on Dec 7, 2022

### ISSUE THREAD

**Issue by masipila** [kimmolinna/pycaruna#6]
Hi,

I guess Caruna has made some changes in their end around 7 December 2022 which caused pycaruna to stop working.

The login method fails:

```
import pycaruna
session = pycaruna.login_caruna("my-username", "my-password")
```
Results in the following traceback...

```
Traceback (most recent call last):
  File "/path/to/pycaruna/fetch.py", line 2, in <module>
    session = pycaruna.login_caruna("my-username", "my-password")
  File "/path/to/pycaruna/pycaruna.py", line 65, in login_caruna
    r = s.get(url)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'e,chrome=1': No schema supplied. Perhaps you meant http://e,chrome=1?
```

Any ideas, anyone?

Cheers,
Markus

**Comment by masipila** [comment]
Must be because of this:

https://caruna.fi/ajankohtaista/olemme-uudistaneet-caruna-plus-tunnistautumispalvelua

**Comment by kimmolinna** [comment]
Fixed.
